# -*- coding: utf-8 -*-
#@Pjname ;GhostApiservice
#@Time   :2019/11/21/02:02
#@Author :GhostGuanyin
#@File   :.travis.yml

language: python
python:
  - 3.6
  - 3.7
  - 3.8
matrix:
  include: # Required for Python 3.6+
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
install:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run coverage run --source=Application
  - poetry run coverage report -m
after_success:
  - poetry run coveralls